### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by samalcolm101** [pcross616/lf-osc-proxy#2]
Hi, you said to leave an issue if I needed some help, so here you go!
I literally have no idea what im doing. I'm quite computer literate so would understand if you were willing to guide me with some more detail than what is written in the readme. I also would need some help writing the macro in lf.

What I am trying to do:

create a link between the osc output on software called isadora (are you familiar with this?) LF and isadora aren't on the same computer but are on the same network. This can change if need be.

I really thank you for taking the time to get back to me!

Thanks,
Sam

**Comment by pcross616** [comment]
Ok, I see a few issues.


  1.
Use the new executable I posted.  Right now all the proxy is listening to is port 3100 and that is not a OSC listener.  you should see this.  (the one you have a screen shot of is the old version)

[cid:Image1210.png@14aa43b42274bb]

  2. If your using the proxy on the same system as your light factory you need to run the proxy with an argument.
lf-osc-proxy-0.2-SNAPSHOT.exe -m osc
  3.  It seems your light factory is listening to port 3200, normally it listens on 3100.  I would suggest to change it back.

  4.  Your Enter Scene Trigger needs to be linked to the Value dot, not the use type

  5.  Your OSC Transmit should point to the system with the proxy running above (in line 1).

  6.  The OSC Transmit address should be:
        /lf/192.168.1.2:3100/cue 4 go

  7.  Depending on the version of Isadora there was an option I had when I right clicked on the OSC Transmit Actor to upgrade the actor to the new format.  I had better luck with that actor once I did that.

That should be it.  I will jump online in the morning around 7:30 am my time which will be about 3:30 pm your time if you want to hop on Skype.

Pete

Sent from Windows Mail

**Comment by pcross616** [comment]
There was a bug in 0.2 with incoming OSC events closing prior to the complete LF command execution.  Outbound worked fine.

Fixed in 0.3
